-d C:\Users\Lithromantic\Desktop\tang_nano_4k\led_test\impl\gwsynthesis\led_test.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst C:\Users\Lithromantic\Desktop\tang_nano_4k\led_test\src\led_test.cst
-cfg C:\Users\Lithromantic\Desktop\tang_nano_4k\led_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
