`define MEM_HYPERRAM
`define DEF_ADDR_WIDTH 22
`define SRAM_DATA_WIDTH_32
`define DEF_SRAM_DATA_WIDTH 32
`define DEF_BURST_WRITE_LENGTH 128
`define DEF_BURST_READ_LENGTH 128
`define WR_VIDEO_WIDTH_16
`define DEF_WR_VIDEO_WIDTH 16
`define RD_VIDEO_WIDTH_16
`define DEF_RD_VIDEO_WIDTH 16
`define DEF_IMAGE_SIZE 32'h00100000
`define USE_THREE_FRAME_BUFFER
`define WRITE_FIFO_DEPTH_1024
`define DEF_WRITE_FIFO_DEPTH 1024
`define READ_FIFO_DEPTH_1024
`define DEF_READ_FIFO_DEPTH 1024
`define READ_FIFO_BURST_MULT 8
